import { StyleSheet, Dimensions, Platform } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  hero: {
    width: "100%",
    backgroundColor: "#101622",
    paddingTop: 60,
    paddingBottom: 80,
    position: "relative",
    overflow: "hidden",
  },
  haloPrimary: {
    position: "absolute",
    top: -100,
    right: -100,
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: "rgba(19, 91, 236, 0.15)",
    ...Platform.select({
      ios: { shadowColor: "#135bec", shadowOpacity: 0.5, shadowRadius: 100 },
      android: { elevation: 20 },
    }),
  },
  container: {
    width: "100%",
    maxWidth: 1280,
    alignSelf: "center",
    paddingHorizontal: 24,
    alignItems: "center",
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(34, 197, 94, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(34, 197, 94, 0.2)",
    marginBottom: 24,
  },
  badgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#22c55e",
    marginRight: 8,
  },
  badgeText: {
    color: "#22c55e",
    fontSize: 13,
    fontWeight: "600",
  },
  title: {
    fontSize: width > 768 ? 56 : 38,
    fontWeight: "900",
    color: "#ffffff",
    textAlign: "center",
    lineHeight: width > 768 ? 64 : 44,
    marginBottom: 20,
  },
  gradientText: {
    color: "#135bec",
  },
  description: {
    fontSize: 17,
    color: "#94a3b8",
    textAlign: "center",
    lineHeight: 26,
    maxWidth: 700,
    marginBottom: 40,
  },
  buttonGroup: {
    flexDirection: width > 480 ? "row" : "column",
    gap: 16,
    width: width > 480 ? "auto" : "100%",
    marginBottom: 60,
  },
  btnPrimary: {
    backgroundColor: "#135bec",
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  btnTextPrimary: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  btnSecondary: {
    backgroundColor: "transparent",
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#282e39",
    alignItems: "center",
  },
  btnTextSecondary: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  visualWrapper: {
    width: "100%",
    maxWidth: 800,
    backgroundColor: "#161a23",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#282e39",
    overflow: "hidden",
  },
  cardContent: {
    padding: 24,
    flexDirection: width > 768 ? "row" : "column",
    gap: 24,
    alignItems: "center",
  },
  editor: {
    flex: 1,
    width: "100%",
  },
  dots: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 20,
  },
  dot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  codeLine: {
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
    fontSize: 14,
    color: "#9da6b9",
    lineHeight: 22,
  },
  indent: {
    marginLeft: 20,
  },
  purple: { color: "#c678dd" },
  blue: { color: "#61afef" },
  green: { color: "#98c379" },
  profileImageWrapper: {
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 4,
    borderColor: "#282e39",
    overflow: "hidden",
  },
  profileImage: {
    width: "100%",
    height: "100%",
  },
});
